/**
 * Visa-risk rule DSL.
 *
 * A rule's `condition` column is a JSON predicate authored by admins. The
 * shape below is intentionally small — five operators and three combinators —
 * so it can be edited from a form without a parser, serialized as-is into
 * Prisma, and round-tripped to an LLM for natural-language → rule synthesis
 * later (see "AI-ready" below).
 *
 * Evaluation is pure and synchronous. The applicant profile is a flat record
 * built from the public form payload; the evaluator dereferences `field` by
 * string lookup. Unknown fields evaluate as `null` and most operators treat
 * `null` as "does not match" — except `notExists`, which matches.
 *
 * AI-ready:
 *   - Field names are stable string keys, listed in PROFILE_FIELDS below.
 *     New rules can be generated by an LLM constrained to those keys.
 *   - Operators are enumerated; no escape hatch, no eval'd expressions.
 *   - The same predicate format is the only thing the engine consumes —
 *     swap the rule source (DB, LLM, A/B variant) without changing the eval.
 */

export type LeafOp =
  | "eq"
  | "ne"
  | "lt"
  | "lte"
  | "gt"
  | "gte"
  | "in"
  | "between"
  | "exists"
  | "notExists";

export interface LeafPredicate {
  kind: "leaf";
  field: string;
  op: LeafOp;
  /** Operator-dependent: scalar for eq/ne/lt/…, [lo, hi] for between, array for in. */
  value?: unknown;
}

export interface AllPredicate {
  kind: "all";
  predicates: Predicate[];
}

export interface AnyPredicate {
  kind: "any";
  predicates: Predicate[];
}

export interface NotPredicate {
  kind: "not";
  predicate: Predicate;
}

export type Predicate = LeafPredicate | AllPredicate | AnyPredicate | NotPredicate;

/**
 * Canonical applicant profile passed to the evaluator. The public form maps
 * its raw payload onto this shape so admin-authored rules reference stable
 * field names regardless of the form's wire format.
 *
 * Keep this list in sync with PROFILE_FIELDS below — the admin editor uses
 * that list to populate the field dropdown so admins can only pick valid
 * keys.
 */
export interface ApplicantProfile {
  // Destination + nationality
  countryCode?: string | null;
  nationalityCode?: string | null;

  // Academic
  gpa?: number | null;
  gpaScale?: number | null; // 4 | 10 | 100 — used to normalize gpa
  educationLevel?: string | null; // "12th" | "Bachelors" | "Masters" | …
  fieldOfStudy?: string | null;
  workExperienceYears?: number | null;

  // English
  ielts?: number | null;
  toefl?: number | null;
  pte?: number | null;
  duolingo?: number | null;

  // Study gap (years between last qualification and intended intake)
  studyGapYears?: number | null;

  // Financials
  showFundsUsd?: number | null;
  sponsorRelation?: string | null; // "self" | "parent" | "sibling" | "agency" | "other"
  fundingSource?: string | null; // "savings" | "loan" | "scholarship" | "mixed"
  hasIncomeTaxReturn?: boolean | null;

  // Visa history
  previousVisaRefusals?: number | null;
  previousVisaCountry?: string | null;

  // Other
  age?: number | null;
  preferredIntake?: string | null;

  /** Anything else the form captures — accessible via `field: "extras.x"`. */
  extras?: Record<string, unknown>;
}

/**
 * Field catalog. Used by:
 *   - the admin rule editor (dropdown)
 *   - the LLM rule-synthesis prompt (constrained vocabulary)
 *   - this module's TYPE_BY_FIELD lookup (coerces values before compare)
 */
export const PROFILE_FIELDS = [
  { key: "countryCode", type: "string", label: "Destination country (ISO-2)" },
  { key: "nationalityCode", type: "string", label: "Nationality (ISO-2)" },
  { key: "gpa", type: "number", label: "GPA (raw)" },
  { key: "gpa4", type: "number", label: "GPA (normalized to 4.0)" },
  { key: "educationLevel", type: "string", label: "Education level" },
  { key: "fieldOfStudy", type: "string", label: "Field of study" },
  { key: "workExperienceYears", type: "number", label: "Work experience (years)" },
  { key: "ielts", type: "number", label: "IELTS band" },
  { key: "toefl", type: "number", label: "TOEFL iBT" },
  { key: "pte", type: "number", label: "PTE Academic" },
  { key: "duolingo", type: "number", label: "Duolingo English Test" },
  { key: "englishBand", type: "number", label: "English (normalized 0–9)" },
  { key: "studyGapYears", type: "number", label: "Study gap (years)" },
  { key: "showFundsUsd", type: "number", label: "Show funds (USD)" },
  { key: "sponsorRelation", type: "string", label: "Sponsor relation" },
  { key: "fundingSource", type: "string", label: "Funding source" },
  { key: "hasIncomeTaxReturn", type: "boolean", label: "Has ITR / tax returns" },
  { key: "previousVisaRefusals", type: "number", label: "Previous visa refusals" },
  { key: "previousVisaCountry", type: "string", label: "Refused-by country (ISO-2)" },
  { key: "age", type: "number", label: "Age (years)" },
  { key: "preferredIntake", type: "string", label: "Preferred intake" },
] as const;

export type ProfileFieldKey = (typeof PROFILE_FIELDS)[number]["key"];

const FIELD_TYPE = Object.fromEntries(
  PROFILE_FIELDS.map((f) => [f.key, f.type]),
) as Record<string, "string" | "number" | "boolean">;

// ── Evaluator ──────────────────────────────────────────────────────────────

export function evaluate(predicate: Predicate, profile: ApplicantProfile): boolean {
  switch (predicate.kind) {
    case "leaf":
      return evaluateLeaf(predicate, profile);
    case "all":
      return predicate.predicates.every((p) => evaluate(p, profile));
    case "any":
      return predicate.predicates.some((p) => evaluate(p, profile));
    case "not":
      return !evaluate(predicate.predicate, profile);
  }
}

function evaluateLeaf(leaf: LeafPredicate, profile: ApplicantProfile): boolean {
  const raw = resolveField(leaf.field, profile);
  const fieldType = FIELD_TYPE[leaf.field] ?? inferType(raw);

  switch (leaf.op) {
    case "exists":
      return raw !== null && raw !== undefined && raw !== "";
    case "notExists":
      return raw === null || raw === undefined || raw === "";
    case "eq":
      return compareEq(raw, leaf.value, fieldType);
    case "ne":
      // Missing field shouldn't satisfy `ne` — otherwise a rule like
      // "ielts ne 6.5" would fire on every applicant who never took IELTS.
      if (raw === null || raw === undefined || raw === "") return false;
      return !compareEq(raw, leaf.value, fieldType);
    case "lt":
    case "lte":
    case "gt":
    case "gte":
      return compareNumeric(raw, leaf.value, leaf.op);
    case "between": {
      const [lo, hi] = Array.isArray(leaf.value) ? leaf.value : [];
      return compareNumeric(raw, lo, "gte") && compareNumeric(raw, hi, "lte");
    }
    case "in": {
      if (raw === null || raw === undefined) return false;
      const arr = Array.isArray(leaf.value) ? leaf.value : [];
      if (fieldType === "string") {
        const s = String(raw).toLowerCase();
        return arr.some((v) => String(v).toLowerCase() === s);
      }
      return arr.some((v) => compareEq(raw, v, fieldType));
    }
  }
}

/**
 * Look up a (possibly nested) field on the profile. Supports synthetic fields
 * `gpa4` and `englishBand` which are computed from the raw inputs.
 */
function resolveField(field: string, profile: ApplicantProfile): unknown {
  if (field === "gpa4") return normalizeGpa4(profile);
  if (field === "englishBand") return normalizeEnglishBand(profile);
  if (field.startsWith("extras.")) {
    return (profile.extras ?? {})[field.slice("extras.".length)] ?? null;
  }
  return (profile as unknown as Record<string, unknown>)[field] ?? null;
}

function compareEq(a: unknown, b: unknown, fieldType: "string" | "number" | "boolean"): boolean {
  if (a === null || a === undefined) return false;
  if (fieldType === "string") return String(a).toLowerCase() === String(b ?? "").toLowerCase();
  if (fieldType === "number") return Number(a) === Number(b);
  if (fieldType === "boolean") return Boolean(a) === Boolean(b);
  return a === b;
}

function compareNumeric(a: unknown, b: unknown, op: "lt" | "lte" | "gt" | "gte"): boolean {
  if (a === null || a === undefined || b === null || b === undefined) return false;
  const x = Number(a);
  const y = Number(b);
  if (!Number.isFinite(x) || !Number.isFinite(y)) return false;
  if (op === "lt") return x < y;
  if (op === "lte") return x <= y;
  if (op === "gt") return x > y;
  return x >= y;
}

function inferType(v: unknown): "string" | "number" | "boolean" {
  if (typeof v === "number") return "number";
  if (typeof v === "boolean") return "boolean";
  return "string";
}

/**
 * Normalize GPA to a 4.0 scale using `gpaScale` when supplied; otherwise
 * detect heuristically. Returns null if no gpa was provided.
 */
export function normalizeGpa4(profile: ApplicantProfile): number | null {
  const g = profile.gpa;
  if (typeof g !== "number" || !Number.isFinite(g)) return null;
  const scale = profile.gpaScale ?? (g <= 4 ? 4 : g <= 10 ? 10 : 100);
  if (scale === 4) return Math.max(0, Math.min(4, g));
  if (scale === 10) return Math.max(0, Math.min(4, (g / 10) * 4));
  return Math.max(0, Math.min(4, (g / 100) * 4));
}

/** Normalize whichever English test is present to an IELTS-equivalent band (0–9). */
export function normalizeEnglishBand(profile: ApplicantProfile): number | null {
  if (typeof profile.ielts === "number") return profile.ielts;
  if (typeof profile.toefl === "number") return toeflToIelts(profile.toefl);
  if (typeof profile.pte === "number") return pteToIelts(profile.pte);
  if (typeof profile.duolingo === "number") return duolingoToIelts(profile.duolingo);
  return null;
}

function toeflToIelts(t: number): number {
  // Coarse mapping based on ETS/IELTS concordance.
  if (t >= 118) return 9;
  if (t >= 110) return 8.5;
  if (t >= 102) return 8;
  if (t >= 94) return 7.5;
  if (t >= 79) return 7;
  if (t >= 60) return 6.5;
  if (t >= 46) return 6;
  if (t >= 35) return 5.5;
  return 5;
}

function pteToIelts(p: number): number {
  if (p >= 89) return 9;
  if (p >= 84) return 8.5;
  if (p >= 79) return 8;
  if (p >= 73) return 7.5;
  if (p >= 65) return 7;
  if (p >= 58) return 6.5;
  if (p >= 50) return 6;
  if (p >= 42) return 5.5;
  return 5;
}

function duolingoToIelts(d: number): number {
  if (d >= 155) return 9;
  if (d >= 140) return 8;
  if (d >= 125) return 7.5;
  if (d >= 115) return 7;
  if (d >= 105) return 6.5;
  if (d >= 95) return 6;
  if (d >= 85) return 5.5;
  return 5;
}
